const foodAllergens = [
  "cereals",
  "gluten",
  "wheat",
  "spelt",
  "khorasan",
  "rye",
  "barley",
  "oats",
  "crustaceans",
  "eggs",
  "fish",
  "peanuts",
  "crabs",
  "lobsters",
  "prawns",
  "shrimp",
  "crawfish",
  "krill",
  "barnacles",
  "crayfish",
  "langoustines",
  "scampi",
  "shellfish",
  "soybeans",
  "milk",
  "lactose",
  "almonds",
  "hazelnuts",
  "walnuts",
  "cashews",
  "pecan nuts",
  "brazil nuts",
  "pistachio nuts",
  "macadamia nuts",
  "queensland nuts",
  "nuts",
  "celery",
  "mustard",
  "sesame seeds",
  "sesame",
  "sulphur dioxide",
  "sulphites",
  "lupin",
  "molluscs",
];

const cosmeticAllergens = [
  "latex",
  "amyl cinnamal",
  "amylcinnamyl alcohol",
  "anisyl alcohol",
  "benzyl alcohol",
  "benzyl benzoate",
  "benzyl cinnamate",
  "benzyl salicylate",
  "cinnamyl alcohol",
  "cinnamaldehyde",
  "citral",
  "citronellol",
  "coumarin",
  "eugenol",
  "farnesol",
  "geraniol",
  "hexyl cinnamaladehyde",
  "hydroxycitronellal",
  "hydroxyisohexyl 3-cyclohexene carboxaldehyde",
  "hicc",
  "lyral",
  "isoeugenol",
  "lilial",
  "d-limonene",
  "linalool",
  "methyl 2-octynoate",
  "g-methylionone",
  "oak moss extract",
  "tree moss extract",
  "methylisothiazolinoneexternal link disclaimer",
  "mit",
  "methylchloroisothiazolinone",
  "cmit",
  "formaldehyde",
  "bronopol",
  "2-bromo-2-nitropropane-1,3-diol",
  "5-bromo-5-nitro-1,3-dioxane",
  "diazolidinyl urea",
  "dmdm hydantoin",
  "1,3-dimethylol-5,5-dimethylhydantoin",
  "imidazolidinyl urea",
  "sodium hydroxymethylglycinate",
  "quaternium-15",
  "dowicil 200",
  "n-(3-chloroallyl) hexaminium chloride",
  "p-phenylenediamine",
  "ppd",
  "coal-tar",
  "nickel",
  "gold",
];
