export const nutValuesTranslationsArray = {
  קלוריות: "calories",
  אנרגיה: "Energy",
  שומנים: "Fat",
  נתרן: "Sodium",
  מלח: "Sodium",
  מלחים: "Sodium",
  "סך הפחמימות": "Carbohydrates",
  פחמימות: "Carbohydrates",
  "סוכרים מתוך פחמימות": "Sugar",
  "סיבים תזונתיים": "Dietary fibers",
  חלבונים: "Proteins",
  סידן: "Calcium",
  ברזל: "Iron",
  מגנזיום: "Magnesium",
  זרחן: "Potassium",
  "חומצות שומן טראנס": "Trans fatty acids",
  "חומצות שומן רוויות": "Saturated fat",
  כולסטרול: "Cholesterol",
  "סוכרים: לקטוז": "Lactose",
  לקטוז: "Lactose",
  "מתוכם סוכר מוסף": "Added sugar",
  "ויטמין‎ B2": "Vitamin B2",
  "ויטמין‎ B3": "Vitamin B3",
  "ויטמין‎ B5": "Vitamin B5",
  "ויטמין‎ B6": "Vitamin B6",
  "ויטמין‎ B12": "Vitamin B12",
  "ויטמין‎ D": "Vitamin D",
  "ויטמין D": "Vitamin D",
  "ויטמין B2": "Vitamin B2",
  "ויטמין B3": "Vitamin B3",
  "ויטמין B5": "Vitamin B5",
  "ויטמין B6": "Vitamin B6",
  "ויטמין B12": "Vitamin B12",
  "חומצה פולית": "Folate",
  גרם: "g",
  מג: "mg",
  מג: "mg",
  מקג: "Mcg",
};

export const glutenIngredients = [
  "wheat",
  "wheatberries",
  "durum",
  "emmer",
  "semolina",
  "spelt",
  "farina",
  "farro",
  "graham",
  "kamut khorasan wheat",
  "einkorn wheat",
  "rye",
  "barley",
  "triticale",
  "malted barley flour",
  "malted milk or milkshakes",
  "malt extract",
  "malt syrup",
  "malt flavoring",
  "malt vinegar",
  "brewer’s yeast",
  "wheat starch",
  "gluten",
];

export const lactoseIngredients = ["milk", "lactose", "whey", "curds"];

export const notVeganIngredients = [
  "lard",
  "meat",
  "fish",
  "chicken",
  "beef",
  "pork",
  "adrenaline",
  "albumen",
  "allantoin",
  "alligator skin",
  "amerchol l101",
  "aminosuccinate acid",
  "aspartic acid",
  "animal",
  "arachidonic acid",
  "arachidyl proprionate",
  "bee",
  "blood",
  "bone",
  "calf",
  "carmine",
  "cochineal",
  "carminic acid",
  "casein",
  "caseinate",
  "sodium caseinate",
  "castor",
  "castoreum",
  "catgut",
  "cerebrosides",
  "cetyl alcohol",
  "cetyl palmitate",
  "cholesterin",
  "cholesterol",
  "cod liver oil",
  "collagen",
  "caprylic",
  "lauric",
  "myristic",
  "palmitic",
  "stearic",
  "fish liver oil",
  "fish oil",
  "feathers",
  "gelatin",
  "glycerides",
  "glycerol",
  "glyceryls",
  "glycreth-26",
  "guanine",
  "pearl essence",
  "hide glue",
  "honey",
  "horsehair",
  "hydrocortisone",
  "animal protein",
  "isinglass",
  "stearyl alcohol",
  "oleic acid",
  "tallow",
  "oleyl arachidate",
  "oleyl imidazoline",
  "myristic acid",
  "oleyl oleate",
  "oleyl stearate",
  "palmitamide",
  "palmitamine",
  "palmitate",
  "palmitic acid",
  "vitamin b-complex factor",
  "provitamin b-5",
  "pepsin",
  "rennet",
  "rennin",
  "placenta",
  "placenta polypeptides protein",
  "polypeptides",
  "polysorbates",
  "progesterone",
  "propolis",
  "royal jelly",
  "sable",
  "turtle",
  "shark",
  "sheep",
  "shellac",
  "resinous glaze",
  "uric acid",
  "wool",
  "whey",
  "egg",
  "lamb",
  "venison",
  "rabbit",
  "duck",
  "goose",
  "turkey",
  "quail",
  "pheasant",
  "partridge",
];

export const nonVegetarianIngredients = [
  "gelatin",
  "rennet",
  "diglycerides",
  "monolycerides",
  "meat",
  "pork",
  "lamb",
  "venison",
  "rabbit",
  "duck",
  "goose",
  "turkey",
  "quail",
  "pheasant",
  "partridge",
  "squab",
];

export const siliconeIngredients = [
  "dimethicone",
  "cyclopentasiloxane",
  "dimethiconol",
  "cyclomethicone",
  "phenyl trimethicone",
  "trimethylsiloxysilicate",
  "methicone",
  "amodimethicone",
  "stearyl dimethicone",
  "behenoxy dimethicone",
  "cetearyl methicone",
  "cetyl dimethicone",
  "cyclohexasiloxane",
  "cyclopentasiloxane/dimethicone crosspolymer",
  "dimethicone copolyol",
  "dimethicone crosspolymer",
  "dimethylsiloxane",
  "phenyl dimethicone",
  "polydimethylsiloxane",
  "vinyl dimethicone",
  "hydrolyzed wheat protein pg-propyl silanetriol",
  "lauryl methicone copolyol",
  "bis-peg/ppg-14/14 dimethicone",
  "peg/ppg-18/18 dimethicone",
  "stearoxy dimethicone",
  "trimethylsilylamodimethicone",
  "triethoxycaprylylsilane",
];

export const microPlasticIngredients = [
  "polyethylene",
  "polypropylene",
  "polyethylene terephthalate",
  "polymethyl methacrylate",
  "nylon-12",
  "nylon-6",
  "nylon-66",
  "acrylates copolymer",
  "acrylates crosspolymer",
  "polyurethane",
  "polystyrene",
  "polytetrafluoroethylene",
  "methyl methacrylate",
  "sodium styrene/divinylbenzene copolymer",
  "polyethylene/polypropylene copolymer",
  "polyethylene/vinyl acetate copolymer",
  "polyvinyl alcohol",
  "ethylene/va copolymer",
  "polyquaternium-7",
  "polyquaternium-11",
  "polyamide-12",
  "polycaprolactone",
  "polyhydroxyethyl methacrylate",
  "ethylene/propylene/styrene copolymer",
  "butylene/ethylene/styrene copolymer",
  "polyurethane-11",
  "polyurethane-33",
  "pvc",
];
